# Analysis: Rebuild Table 1 in a JAMA-style layout using locked overlap weights
# Date: 2026-08-19
# Random seed: not applicable (deterministic descriptive summarisation)
# R: 4.4.2
#
# Purpose: Reformat the publication Table 1 as one two-cohort balance table,
#          consistent with Gupta et al. (JAMA Internal Medicine 2026), while
#          preserving the locked, completed datasets and their stored ATO weights.
# Source code/method: WeightIt overlap weighting with bias-reduced logistic regression;
#                     locked weight objects generated by 03_fit_cbps_ate_weights.R.
# Citation/version: Li F, Morgan KL, Zaslavsky AM. JASA. 2018;113:390-400;
#                   Gupta AB, et al. JAMA Intern Med. 2026;186:192-202.
# Access date: 2026-08-19
# Adaptation: no propensity-score or outcome model is refitted. Each of 20 locked
#             completed datasets is summarised with its stored ATO weights; displayed
#             descriptive statistics are arithmetic means across completed datasets.
# Verification command:
#   D:/software/R4.4.2/R-4.4.2/bin/x64/Rscript.exe --vanilla 22_rebuild_table1_jama_style_ato.R

options(stringsAsFactors = FALSE)

if (!requireNamespace("flextable", quietly = TRUE) ||
    !requireNamespace("officer", quietly = TRUE)) {
  stop("Packages 'flextable' and 'officer' are required.")
}

script_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
if (length(script_arg) != 1L) stop("Run this script with Rscript.")
script_path <- normalizePath(sub("^--file=", "", script_arg), winslash = "/", mustWork = TRUE)
project_root <- normalizePath(Sys.getenv("TTE_PROJECT_ROOT", unset = "."), winslash = "/", mustWork = TRUE)
runtime_root <- normalizePath(Sys.getenv("TTE_RUNTIME_ROOT", unset = "."), winslash = "/", mustWork = TRUE)

# Locked ATO weight objects contain the 20 completed MICE datasets and weights.
weight_root <- file.path(runtime_root, "09_输出结果", "03_权重")
data_dir <- file.path(project_root, "data")
out_csv <- file.path(data_dir, "Table 1_Weighted Baseline Characteristics.csv")
out_docx <- file.path(data_dir, "Table 1_Weighted Baseline Characteristics.docx")

trials <- c("anti_mrsa", "anti_psa")
trial_labels <- c(
  anti_mrsa = "Anti-MRSA",
  anti_psa = "Anti-pseudomonal"
)

# The rows retain the clinical covariate set in the locked main propensity-score model.
row_spec <- list(
  list(type = "section", label = "Demographic characteristics"),
  list(type = "continuous", field = "age_years", label = "Age, median (IQR), y", digits = 1),
  list(type = "binary", field = "male", level = "1", label = "Male sex", digits = 1),
  list(type = "section", label = "Baseline health information"),
  list(type = "binary", field = "diabetes_mellitus", level = "1", label = "Diabetes mellitus", digits = 1),
  list(type = "binary", field = "congestive_heart_failure", level = "1", label = "Congestive heart failure", digits = 1),
  list(type = "binary", field = "chronic_obstructive_pulmonary_disease", level = "1", label = "Chronic obstructive pulmonary disease", digits = 1),
  list(type = "binary", field = "chronic_kidney_disease", level = "1", label = "Chronic kidney disease", digits = 1),
  list(type = "binary", field = "hematologic_malignancy", level = "1", label = "Hematologic malignancy", digits = 1),
  list(type = "binary", field = "solid_malignancy", level = "1", label = "Solid malignancy", digits = 1),
  list(type = "categorical_header", field = "liver_disease_severity", label = "Liver disease severity"),
  list(type = "categorical_level", field = "liver_disease_severity", level = 0, label = "  None", digits = 1),
  list(type = "categorical_level", field = "liver_disease_severity", level = 1, label = "  Mild", digits = 1),
  list(type = "categorical_level", field = "liver_disease_severity", level = 2, label = "  Moderate or severe", digits = 1),
  list(type = "binary", field = "immunosuppression", level = "1", label = "Immunosuppression", digits = 1),
  list(type = "section", label = "Early hospitalization data (before index time)"),
  list(type = "categorical_header", field = "sepsis_onset_setting", label = "Sepsis-onset setting"),
  list(type = "categorical_level", field = "sepsis_onset_setting", level = "1", label = "  Early after hospital admission", digits = 1),
  list(type = "categorical_level", field = "sepsis_onset_setting", level = "2", label = "  After admission, before ICU", digits = 1),
  list(type = "categorical_level", field = "sepsis_onset_setting", level = "3", label = "  During ICU stay", digits = 1),
  list(type = "categorical_header", field = "infection_site_group5", label = "Infection site"),
  list(type = "categorical_level", field = "infection_site_group5", level = "1", label = "  Respiratory", digits = 1),
  list(type = "categorical_level", field = "infection_site_group5", level = "2", label = "  Genitourinary", digits = 1),
  list(type = "categorical_level", field = "infection_site_group5", level = "3", label = "  Multiple sites", digits = 1),
  list(type = "categorical_level", field = "infection_site_group5", level = "4", label = "  Other identified", digits = 1),
  list(type = "categorical_level", field = "infection_site_group5", level = "5", label = "  Undetermined", digits = 1),
  list(type = "categorical_header", field = "source_control_status", label = "Source-control procedure status"),
  list(type = "categorical_level", field = "source_control_status", level = "0", label = "  Not recorded", digits = 1),
  list(type = "categorical_level", field = "source_control_status", level = "1", label = "  Recorded", digits = 1),
  list(type = "categorical_level", field = "source_control_status", level = "9", label = "  Unknown", digits = 1),
  list(type = "categorical_header", field = "microbiology_state_group4", label = "Microbiology status at index time"),
  list(type = "categorical_level", field = "microbiology_state_group4", level = "0", label = "  All final results negative", digits = 1),
  list(type = "categorical_level", field = "microbiology_state_group4", level = "1", label = "  Non-target organism positive", digits = 1),
  list(type = "categorical_level", field = "microbiology_state_group4", level = "2", label = "  Unresolved at index time", digits = 1),
  list(type = "categorical_level", field = "microbiology_state_group4", level = "3", label = "  No culture obtained", digits = 1),
  list(type = "categorical_header", field = "other_broad_spectrum_antibiotics", label = "Other broad-spectrum antibiotic exposure"),
  list(type = "categorical_level", field = "other_broad_spectrum_antibiotics", level = "0", label = "  None", digits = 1),
  list(type = "categorical_level", field = "other_broad_spectrum_antibiotics", level = "1", label = "  One class", digits = 1),
  list(type = "categorical_level", field = "other_broad_spectrum_antibiotics", level = "2", label = "  Two or more classes", digits = 1),
  list(type = "binary", field = "nephrotoxic_drug_exposure", level = "1", label = "Nephrotoxic drug exposure", digits = 1),
  list(type = "section", label = "Clinical trajectory at the index time"),
  list(type = "continuous", field = "baseline_creatinine_mg_dl", label = "Baseline serum creatinine, mg/dL", digits = 1),
  list(type = "continuous", field = "target_antibiotic_administration_count_72h", label = "Target-antibiotic administrations during first 72 h", digits = 1),
  list(type = "continuous", field = "recent_nonrenal_sofa", label = "Most recent pre-index nonrenal SOFA score", digits = 1),
  list(type = "continuous", field = "nonrenal_sofa_change", label = "Change in nonrenal SOFA score", digits = 1),
  list(type = "continuous", field = "creatinine_change_mg_dl", label = "Pre-index change in serum creatinine, mg/dL", digits = 1),
  list(type = "continuous", field = "urine_output_rate_6h_ml_kg_h", label = "6-h urine-output rate, mL/kg/h", digits = 1)
)

weighted_mean <- function(x, w) sum(x * w) / sum(w)
weighted_var <- function(x, w) {
  m <- weighted_mean(x, w)
  sum(w * (x - m)^2) / sum(w)
}
weighted_quantile <- function(x, w, probs = c(0.25, 0.50, 0.75)) {
  keep <- is.finite(x) & is.finite(w) & w > 0
  x <- x[keep]
  w <- w[keep]
  if (!length(x)) return(rep(NA_real_, length(probs)))
  ord <- order(x)
  x <- x[ord]
  w <- w[ord]
  cw <- cumsum(w) / sum(w)
  stats::approx(x = c(0, cw), y = c(x[1L], x), xout = probs, method = "linear", rule = 2, ties = "ordered")$y
}
weighted_binary_summary <- function(x, w, treatment, level) {
  x <- as.character(x) == as.character(level)
  output <- lapply(c(1L, 0L), function(a) {
    idx <- treatment == a
    p <- weighted_mean(as.numeric(x[idx]), w[idx])
    n_raw <- sum(idx)
    c(pseudo_n = n_raw * p, pct = 100 * p)
  })
  p1 <- unname(output[[1L]]["pct"] / 100)
  p0 <- unname(output[[2L]]["pct"] / 100)
  smd <- (p1 - p0) / sqrt((p1 * (1 - p1) + p0 * (1 - p0)) / 2)
  c(de_n = unname(output[[1L]]["pseudo_n"]), de_pct = unname(output[[1L]]["pct"]),
    co_n = unname(output[[2L]]["pseudo_n"]), co_pct = unname(output[[2L]]["pct"]), smd = unname(smd))
}
weighted_continuous_summary <- function(x, w, treatment) {
  output <- lapply(c(1L, 0L), function(a) {
    idx <- treatment == a
    q <- weighted_quantile(x[idx], w[idx])
    c(q1 = q[1L], median = q[2L], q3 = q[3L], mean = weighted_mean(x[idx], w[idx]), variance = weighted_var(x[idx], w[idx]))
  })
  smd <- (unname(output[[1L]]["mean"]) - unname(output[[2L]]["mean"])) /
    sqrt((unname(output[[1L]]["variance"]) + unname(output[[2L]]["variance"])) / 2)
  c(de_q1 = unname(output[[1L]]["q1"]), de_median = unname(output[[1L]]["median"]), de_q3 = unname(output[[1L]]["q3"]),
    co_q1 = unname(output[[2L]]["q1"]), co_median = unname(output[[2L]]["median"]), co_q3 = unname(output[[2L]]["q3"]), smd = unname(smd))
}
format_count_pct <- function(n, p, digits = 1) sprintf(paste0("%.", digits, "f (%.1f)"), n, p)
format_median_iqr <- function(q1, median, q3, digits = 1) sprintf(paste0("%.", digits, "f (%.", digits, "f to %.", digits, "f)"), median, q1, q3)
format_smd <- function(x) {
  if (!is.finite(x)) return("")
  if (abs(x) < 0.001) return("<0.001")
  sprintf("%.3f", abs(x))
}

summarise_specification <- function(trial, spec) {
  imputation_summaries <- lapply(seq_len(20L), function(m) {
    path <- file.path(weight_root, sprintf("weights_%s_imp%02d.rds", trial, m))
    if (!file.exists(path)) stop("Missing locked weight object: ", path)
    saved <- readRDS(path)
    if (!identical(saved$trial, trial) || saved$imputation != m) stop("Weight-object identity check failed: ", path)
    data <- saved$completed_data
    if (!spec$field %in% names(data)) stop("Missing field in locked completed data: ", spec$field)
    treatment <- as.integer(as.character(data$deescalation))
    if (!identical(sort(unique(treatment)), c(0L, 1L))) stop("Unexpected treatment coding in ", path)
    weights <- saved$ato_brlogit$weight
    if (length(weights) != nrow(data) || any(!is.finite(weights)) || any(weights <= 0)) stop("Invalid stored ATO weights in ", path)
    if (identical(spec$type, "continuous")) {
      weighted_continuous_summary(as.numeric(data[[spec$field]]), weights, treatment)
    } else {
      weighted_binary_summary(data[[spec$field]], weights, treatment, spec$level)
    }
  })
  summary <- colMeans(do.call(rbind, imputation_summaries))
  maximum_absolute_smd <- max(abs(vapply(
    imputation_summaries,
    function(x) unname(x["smd"]),
    numeric(1)
  )))
  if (identical(spec$type, "continuous")) {
    c(de = format_median_iqr(summary["de_q1"], summary["de_median"], summary["de_q3"], spec$digits),
      co = format_median_iqr(summary["co_q1"], summary["co_median"], summary["co_q3"], spec$digits),
      smd = format_smd(maximum_absolute_smd))
  } else {
    c(de = format_count_pct(summary["de_n"], summary["de_pct"], spec$digits),
      co = format_count_pct(summary["co_n"], summary["co_pct"], spec$digits),
      smd = format_smd(maximum_absolute_smd))
  }
}

raw_n <- sapply(trials, function(trial) {
  path <- file.path(weight_root, sprintf("weights_%s_imp01.rds", trial))
  x <- readRDS(path)$completed_data$deescalation
  c(deescalation = sum(as.character(x) == "1"), continuation = sum(as.character(x) == "0"))
})

table_rows <- lapply(row_spec, function(spec) {
  if (identical(spec$type, "section")) {
    return(c(Characteristic = spec$label, MRSA_de = "", MRSA_co = "", MRSA_smd = "", PSA_de = "", PSA_co = "", PSA_smd = ""))
  }
  if (identical(spec$type, "categorical_header")) {
    # Categorical SMD is supplied on the header row as the maximum absolute level-specific SMD.
    return(c(Characteristic = spec$label, MRSA_de = "", MRSA_co = "", MRSA_smd = "", PSA_de = "", PSA_co = "", PSA_smd = ""))
  }
  mrsa <- summarise_specification("anti_mrsa", spec)
  psa <- summarise_specification("anti_psa", spec)
  c(Characteristic = spec$label, MRSA_de = mrsa["de"], MRSA_co = mrsa["co"], MRSA_smd = mrsa["smd"], PSA_de = psa["de"], PSA_co = psa["co"], PSA_smd = psa["smd"])
})

# Categorical header SMDs require the maximum absolute SMD over every listed level.
for (i in seq_along(row_spec)) {
  spec <- row_spec[[i]]
  if (!identical(spec$type, "categorical_header")) next
  level_rows <- which(vapply(row_spec, function(x) identical(x$field, spec$field) && identical(x$type, "categorical_level"), logical(1)))
  header_pos <- i
  for (smd_col in c(4L, 7L)) {
    vals <- vapply(level_rows, function(pos) suppressWarnings(as.numeric(gsub("<0.001", "0.0005", table_rows[[pos]][smd_col], fixed = TRUE))), numeric(1))
    max_val <- max(vals, na.rm = TRUE)
    table_rows[[header_pos]][smd_col] <- if (is.finite(max_val)) format_smd(max_val) else ""
    for (pos in level_rows) table_rows[[pos]][smd_col] <- ""
  }
}

row_lengths <- lengths(table_rows)
if (any(row_lengths != 7L)) {
  stop("Unexpected Table 1 row width at row(s): ", paste(which(row_lengths != 7L), collapse = ", "))
}
table_df <- as.data.frame(do.call(rbind, lapply(table_rows, unname)), stringsAsFactors = FALSE, check.names = FALSE)
names(table_df) <- c(
  "Characteristic",
  "Anti-MRSA: De-escalation", "Anti-MRSA: Continuation", "Anti-MRSA: SMD",
  "Anti-pseudomonal: De-escalation", "Anti-pseudomonal: Continuation", "Anti-pseudomonal: SMD"
)
utils::write.csv(table_df, out_csv, row.names = FALSE, na = "", fileEncoding = "UTF-8")

# A JAMA-like three-level header, landscape orientation, editable Word table, and no vertical rules.
header_df <- data.frame(
  col_keys = names(table_df),
  header1 = c("Characteristic", rep("Anti-MRSA coverage cohort", 3L), rep("Anti-pseudomonal coverage cohort", 3L)),
  header2 = c("", "", "", "", "", "", ""),
  header3 = c(
    "",
    sprintf("De-escalation (n = %d)", raw_n["deescalation", "anti_mrsa"]),
    sprintf("Continuation (n = %d)", raw_n["continuation", "anti_mrsa"]),
    "SMD",
    sprintf("De-escalation (n = %d)", raw_n["deescalation", "anti_psa"]),
    sprintf("Continuation (n = %d)", raw_n["continuation", "anti_psa"]),
    "SMD"
  ),
  check.names = FALSE
)

ft <- flextable::flextable(table_df)
ft <- flextable::set_header_df(ft, mapping = header_df, key = "col_keys")
ft <- flextable::merge_h(ft, part = "header")
ft <- flextable::merge_v(ft, j = 1, part = "header")
ft <- flextable::merge_at(ft, i = 1, j = 2:4, part = "header")
ft <- flextable::merge_at(ft, i = 1, j = 5:7, part = "header")
ft <- flextable::theme_booktabs(ft)
ft <- flextable::border_remove(ft)
ft <- flextable::hline_top(ft, border = officer::fp_border(color = "000000", width = 1.25), part = "header")
ft <- flextable::hline(ft, i = 3, border = officer::fp_border(color = "000000", width = 0.75), part = "header")
ft <- flextable::hline_bottom(ft, border = officer::fp_border(color = "000000", width = 1.25), part = "body")
ft <- flextable::bold(ft, part = "header")
ft <- flextable::font(ft, fontname = "Times New Roman", part = "all")
ft <- flextable::fontsize(ft, size = 8, part = "all")
ft <- flextable::align(ft, j = 1, align = "left", part = "all")
ft <- flextable::align(ft, j = 2:7, align = "center", part = "all")
ft <- flextable::valign(ft, valign = "center", part = "all")
ft <- flextable::padding(ft, padding.top = 2, padding.bottom = 2, padding.left = 3, padding.right = 3, part = "all")
ft <- flextable::width(ft, j = 1, width = 2.55)
ft <- flextable::width(ft, j = c(2, 3, 5, 6), width = 1.25)
ft <- flextable::width(ft, j = c(4, 7), width = 0.70)
section_rows <- which(vapply(row_spec, function(x) identical(x$type, "section"), logical(1)))
ft <- flextable::bg(ft, bg = "#FFFFFF", part = "body")
ft <- flextable::bold(ft, i = section_rows, j = 1, bold = TRUE, part = "body")
ft <- flextable::set_table_properties(ft, layout = "fixed", opts_word = list(repeat_headers = TRUE, split = TRUE))

section <- officer::prop_section(
  page_size = officer::page_size(orient = "landscape"),
  page_margins = officer::page_mar(top = 0.50, bottom = 0.50, left = 0.45, right = 0.45)
)
doc <- officer::read_docx()
doc <- officer::body_set_default_section(doc, value = section)
doc <- officer::body_add_par(doc, "Table 1. Weighted Baseline Characteristics After Overlap Weighting", style = "Normal")
doc <- flextable::body_add_flextable(doc, value = ft)
note <- paste(
  "Data are weighted median (IQR) for continuous variables and weighted No. (%) for categorical variables.",
  "Weights are the locked overlap weights (ATO) from bias-reduced logistic propensity-score models; no model or outcome was refitted.",
  "Weighted counts are normalised within each treatment strategy to its observed sample size and then averaged across 20 multiply imputed data sets, so they are pseudo-counts rather than observed event counts.",
  "For every row, SMD is the maximum absolute standardised mean difference across the 20 completed data sets; for categorical variables, the SMD on the header row is the largest level-specific value.",
  "ATO indicates average treatment effect in the overlap population; ICU, intensive care unit; IQR, interquartile range; MRSA, methicillin-resistant Staphylococcus aureus; SMD, standardised mean difference."
)
doc <- officer::body_add_fpar(
  doc,
  officer::fpar(
    officer::ftext(paste0("Note. ", note), officer::fp_text(font.family = "Times New Roman", font.size = 8))
  )
)
print(doc, target = out_docx)

cat("TABLE1_CSV=", out_csv, "\n", sep = "")
cat("TABLE1_DOCX=", out_docx, "\n", sep = "")
cat("TABLE1_ESTIMAND=ATO\n")
cat("TABLE1_IMPUTATIONS=20\n")
cat("TABLE1_REBUILD_STATUS=PASS\n")
